# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  name: Default

variables:
  HL_NO_DOCKER: true
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
  - script: |
      bb stack:sync
    displayName: 'Sync with remote'

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | infra/yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages

  - script: |
      cd infra && yarn --frozen-lockfile
    displayName: 'Install all CDK deps'

  - script: |
      bb stack:compile
    displayName: 'Compile project into uberjar'

  - script: |
      bb native:executable
    displayName: 'GraalVM native image compile'

  - script: |
      cd infra && cdk deploy
    displayName: 'CDK deploy'
