# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pool:
  name: Default

variables:
  HL_NO_DOCKER: true

steps:
  - script: |
      bb stack:sync
    displayName: 'Sync with remote'

  - script: |
      bb stack:compile
    displayName: 'Compile'

  - script: |
      bb native:executable
    displayName: 'GraalVM native image compile'
